### ISSUE TITLE
Rework Utils defunct

### ISSUE THREAD

**Issue by j9t** [LeaVerou/rework-utils#1]
Rework Utils don’t work anymore (whether by [invoking directly](https://projects.verou.me/rework-utils/?url=https%3A%2F%2Ffrontenddogma.com%2F), which led me to the issue, or by trying a different URL, or direct input). Could only have a quick look, but it seems one resource (parsel.js) is missing, as it‘s not being found at https://projects.verou.me/parsel/parsel.js.

**Comment by LeaVerou** [comment]
Ah yeah, parsel changed domain and is now under https://parsel.verou.me/dist/parsel.js

Up for sending a quick PR?

**Comment by j9t** [comment]
Sure, filed #2. Not up-to-speed on imports though and whether the update works like this.

**Comment by j9t** [comment]
The #2 update means some progress, @LeaVerou, but another update will be needed to address a CORS issue:

> Access to script at 'https://parsel.verou.me/dist/parsel.js' from origin 'https://projects.verou.me' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by LeaVerou** [comment]
I just made the change, should be fixed in a bit, let me know if not!

**Comment by j9t** [comment]
Seems to work all well again! 🙏
